version: 2.1

jobs:
  ansible-check:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y sshpass
            python -m pip install --upgrade pip
            pip install ansible ansible-lint
      - run:
          name: Prepare vault password
          command: echo "xxx" > /home/circleci/.vaultpass
      - run:
          name: Ansible Syntax Check
          command: |
            export ANSIBLE_CONFIG=ansible.cfg
            ansible-playbook install.yml --syntax-check
      - run:
          name: Ansible Lint
          command: ansible-lint install.yml
      - run:
          name: Cleanup
          command: rm /home/circleci/.vaultpass
workflows:
  version: 2
  ansible-check-workflow:
    jobs:
      - ansible-check
