---
# tasks file for backup
- name: Create backup dir
  file:
    path: /backup/{{ domain }}/mysql/
    state: directory
    owner: root
    group: root
    mode: '0755'
    recurse: true

- name: MySQL-Dump-Skript
  copy:
    dest: /usr/local/bin/mysql_backup_{{ domain }}.sh
    mode: '0755'
    owner: root
    group: root
    content: |
      #!/bin/bash
      BACKUP_DIR="/backup/{{ domain }}/mysql"
      DATE=$(date +%F)
      DUMP_FILE="${BACKUP_DIR}/db-${DATE}.sql.gz"

      mysqldump --defaults-extra-file=/etc/mysql/debian.cnf --all-databases | gzip > "$DUMP_FILE"

      find "$BACKUP_DIR" -type f -name "db-*.sql.gz" -mtime +10 -delete

- name: Cronjob  MySQL-Dump
  cron:
    name: " MySQL-Dump {{ domain }}"
    user: root
    job: "/usr/local/bin/mysql_backup_{{ domain }}.sh"
    minute: 30
    hour: 2
