---
# tasks file for sysprep
- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - curl
    - python3
    - unzip
    - python3-pymysql

- name: Set timezone
  timezone:
    name: Europe/Oslo

- name: Set TERM environment variable
  copy:
    dest: /etc/profile.d/terminal.sh
    mode: '0644'
    content: |
      TERM=xterm
      export TERM

- name: Disable dynamic MOTD scripts
  file:
    path: "/etc/update-motd.d/{{ item }}"
    mode: '0644'
    owner: root
    group: root
    state: absent
  loop:
    - 00-header
    - 10-help-text
    - 50-motd-news
    - 80-livepatch
    - 90-updates-available
    - 91-release-upgrade
    - 95-hwe-eol
    - 97-overlayroot
    - 98-fsck-at-reboot
    - 98-reboot-required
    - 99-footer
  tags: motd

- name: Remove /etc/motd.dynamic if present
  file:
    path: /etc/motd.dynamic
    state: absent
  tags: motd

- name: Disable pam_motd (dynamic MOTD via PAM)
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: '^session\s+optional\s+pam_motd.so'
    state: absent
  tags: motd

- name: Disable pam_motd for login shell
  lineinfile:
    path: /etc/pam.d/login
    regexp: '^session\s+optional\s+pam_motd.so'
    state: absent
  tags: motd

- name: Set custom MOTD with project info
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    mode: '0644'
    owner: root
    group: root

- name: Ensure pam_motd shows only static /etc/motd
  lineinfile:
    path: /etc/pam.d/sshd
    line: 'session optional pam_motd.so motd=/etc/motd'
    create: true
